### ISSUE TITLE
server

### ISSUE THREAD

**Issue by knkrth** [adonespitogo/AdoBot-IO#1]

**Comment by knkrth** [comment]
How to change ./config/config.json  setting for development on localhost?

**Comment by adonespitogo** [comment]
```
"development": {

    "username": "root",

    "password": null,

    "database": "adobot",

    "host": "127.0.0.1",

    "dialect": "mysql",

    "admin" : {

      "username": "admin",

      "password": "admin"

    }

  }
```

This is a configuration for database. The `admin` section refers to admin panel login credentials.

**Comment by knkrth** [comment]
Thanks.

**Comment by adonespitogo** [comment]
After setting up the database, run `./node_modules/.bin/sequelize db:migrate` to create the db tables

**Comment by knkrth** [comment]
Ok.

**Comment by knkrth** [comment]
I got this error on npm install

   `Sequelize [Node: 8.9.3, CLI: 2.7.0, ORM: 3.30.4]

    Loaded configuration file "config/config.json".
    Using environment "development".
    /home/ubuntu/adobot/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

    TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:186:11)
    at Object.Auth.token (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/Auth.js:29:29)
    at Handshake._sendCredentials 
    (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/sequences/Handshake.js:78:14)
    at Handshake.HandshakeInitializationPacket 
    (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/sequences/Handshake.js:60:10)
    at Protocol._parsePacket 
    (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/adobot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/adobot/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)`

**Comment by adonespitogo** [comment]
Can you show your config.json file?

**Comment by knkrth** [comment]
My bad. I changed the mysql password from a number to a string now I got new error

`  Sequelize [Node: 8.9.3, CLI: 2.7.0, ORM: 3.30.4]
   reading "config/config.json". Error: SyntaxError: /home/ubuntu/adobot/config/config.json: Unexpected 
   token r in JSON at position 144`

**Comment by adonespitogo** [comment]
Systax error. Make sure your config.json is a valid json file.

**Comment by adonespitogo** [comment]
You're probably missing a comma between fields:

```json
{
  "field": "value"**,**
  ...
}

**Comment by knkrth** [comment]
This my config.json file 

```{
  "defaults": {
    "charset": "utf8mb4",
    "collate": "utf8mb4_unicode_ci"
  },
  "development": {
    "username": "root",
    "password": root,
    "database": "adobot",
    "host": "127.0.0.1",
    "dialect": "mysql",
    "admin" : {
      "username": "admin",
      "password": "admin"
    }
  }```

**Comment by adonespitogo** [comment]
The password field `root` - put it inside quotes so it looks like "password" : "root".

**Comment by knkrth** [comment]
On MYSQL `"password" : password` goes without quotes & there is no line 144 on `config.json`

**Comment by adonespitogo** [comment]
Replace the whole content of your config.json file with the following. The will fix it 

```json
{
  "defaults": {
    "charset": "utf8mb4",
    "collate": "utf8mb4_unicode_ci"
  },
  "development": {
    "username": "root",
    "password": "root",
    "database": "adobot",
    "host": "127.0.0.1",
    "dialect": "mysql",
    "admin" : {
      "username": "admin",
      "password": "admin"
    }
  },
  "production": {
    "use_env_variable": "DATABASE_URL",
    "pool": {
      "max": 5,
      "min": 1,
      "idle": 10000,
      "maxIdleTime": 120000
    },
    "admin": {
      "username": {
        "use_env_variable": "ADMIN_USERNAME"
      } ,
      "password": {
        "use_env_variable": "ADMIN_PASSWORD"
      }
    }
  }
}
```

**Comment by knkrth** [comment]
Everything Works perfect now. Thank you.

**Comment by knkrth** [comment]
Is there any plan on adding `File Manager, Camera, Mic` On it?

**Comment by adonespitogo** [comment]
I'm no longer using this spyware now, so I'm not adding any features. But I'm willing to assist anyone willing to add more feature to the app.

**Comment by knkrth** [comment]
Ok. I'm closing this issue as its been resolved.

**Comment by lordcharlx** [comment]
@knkrth  please can you share or show how  you add the above I mean mic,file manager and camera thanks in advance
