### ISSUE TITLE
how to install web server on local 

### ISSUE THREAD

**Issue by shaikhsiddik** [adonespitogo/AdoBot-IO#23]
i am trying to install web server on local platform but on error occurred like below please help me to achieve my target 
thanks in advance
  

Loaded configuration file "config/config.json".
Using environment "development".
(node:32001) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:32001) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
Unable to connect to database: SequelizeConnectionError: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! androspy@1.0.0 sequelize_it_please: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the androspy@1.0.0 sequelize_it_please script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! androspy@1.0.0 postinstall: `run-s sequelize_it_please gulp_it_please`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the androspy@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log

**Comment by vanshsantoshi** [comment]
A lot of people are facing similar problem , and the developer isn't maintaining it anymore 
Try installing it with remote sql , I've heard that it's working nice that way

**Comment by varunkudalkar** [comment]
This issue can be solved by using an older version of node, Its working fine with node version 11.15.0 and gulp version 3.9.1.
I think the gulp version causes this issue.
