### ISSUE TITLE
there is problem push heroku master

### ISSUE THREAD

**Issue by oathsaviour** [adonespitogo/AdoBot-IO#25]
![heroku1](https://user-images.githubusercontent.com/60757380/75973004-7cfcd200-5efa-11ea-9c9d-ad7c91a4ff1a.jpg)
![heroku2](https://user-images.githubusercontent.com/60757380/75973024-838b4980-5efa-11ea-822f-e3e94130302f.jpg)
![heroku3](https://user-images.githubusercontent.com/60757380/75973029-86863a00-5efa-11ea-8662-b06317bc3812.jpg)

**Comment by adonespitogo** [comment]
Update the package.json dependencies to latest version.

**Comment by oathsaviour** [comment]
I tried.  I think I might be wrong somewhere so please correct me and guide me how to do that

**Comment by carlossaldanha** [comment]
I have the same problem, how do I update the dependencies? tanks

**Comment by oathsaviour** [comment]
I Don't know. I have tried many ways but I failed. And the developer can not help us.

**Comment by kundanSingh11** [comment]
Just add the line
"engines": {
"node": "10.18.x"
},
after
"main": "index.js",

**Comment by carlossaldanha** [comment]
-Dont Work for me, i have this error!

remote:        Done. Phantomjs binary available at /tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
remote:
remote:        > androspy@1.0.0 postinstall /tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f
remote:        > run-s migrate build
remote:
remote:
remote:        > androspy@1.0.0 migrate /tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f
remote:        > sequelize db:migrate
remote:
remote:
remote:        Sequelize [Node: 12.16.1, CLI: 2.7.0, ORM: 3.30.4]
remote:
remote:        fs.js:35
remote:        } = primordials;
remote:            ^
remote:
remote:        ReferenceError: primordials is not defined
remote:            at fs.js:35:5
remote:            at req_ (/tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f/node_modules/natives/index.js:143:24)
remote:            at Object.req [as require] (/tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f/node_modules/natives/index.js:55:10)
remote:            at Object.<anonymous> (/tmp/build_f3a0bbecf9d0350657f9e87d71fe6d8f/node_modules/graceful-fs/fs.js:1:37)
remote:            at Module._compile (internal/modules/cjs/loader.js:1158:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
remote:            at Module.load (internal/modules/cjs/loader.js:1002:32)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:901:14)
remote:            at Module.require (internal/modules/cjs/loader.js:1044:19)
remote:            at require (internal/modules/cjs/helpers.js:77:18)
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! androspy@1.0.0 migrate: `sequelize db:migrate`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the androspy@1.0.0 migrate script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.BtuiT/_logs/2020-04-04T23_42_25_794Z-debug.log
remote:        ERROR: "migrate" exited with 1.
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! androspy@1.0.0 postinstall: `run-s migrate build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the androspy@1.0.0 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.BtuiT/_logs/2020-04-04T23_42_25_863Z-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to andro-sistem.
remote:
To https://git.heroku.com/andro-sistem.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/andro-sistem.git'


-My package.json file config

{
  "name": "androspy",
  "version": "1.0.0",
  "description": "NodeJS port of Dendroid server",
  "main": "index.js",
  "engines": {
  "node": "10.18.x"
  },
  "scripts": {
    "migrate": "./node_modules/.bin/sequelize db:migrate",
    "build": "./node_modules/.bin/gulp",
    "start": "node index.js",
    "postinstall": "run-s migrate build",
    "dev": "run-s build start"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/adonespitogo/dendroid-nodejs.git"
  },
  "keywords": [
    "dendroid",
    "nodejs",
    "express"
  ],
  "author": "Adones Pitogo",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/adonespitogo/dendroid-nodejs/issues"
  },
  "homepage": "https://github.com/adonespitogo/dendroid-nodejs#readme",
  "dependencies": {
    "body-parser": "^1.16.1",
    "del": "^3.0.0",
    "express": "^4.14.1",
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "^2.2.5",
    "gulp-concat": "^2.6.1",
    "gulp-inject": "^5.0.0",
    "gulp-uglify": "^3.0.1",
    "gulp-util": "^3.0.8",
    "mysql": "^2.13.0",
    "natives": "^1.1.6",
    "pg": "^7.9.0",
    "pg-hstore": "^2.3.2",
    "q": "^1.4.1",
    "randomstring": "^1.1.5",
    "require-dir": "^0.3.1",
    "sequelize": "^3.30.2",
    "sequelize-cli": "^2.5.1",
    "socket.io": "^1.7.2"
  },
  "devDependencies": {
    "gulp-jshint": "^2.1.0",
    "gulp-watch": "^4.3.11",
    "jshint": "^2.9.6",
    "npm-run-all": "^4.1.5"
  }
}

**Comment by kundanSingh11** [comment]
the remote is still using node 12
Sequelize [Node: 12.16.1, CLI: 2.7.0, ORM: 3.30.4]

the output should be this
  Sequelize [Node: 10.18.1, CLI: 2.7.0, ORM: 3.30.4]

please delete all the file from remote

then commit again with 
this package.json file

{
  "name": "androspy",
  "version": "1.0.0",
  "description": "NodeJS port of Dendroid server",
  "main": "index.js",
  "engines": {
    "node": "10.18.x"
  },
  "scripts": {
    "migrate": "./node_modules/.bin/sequelize db:migrate",
    "build": "./node_modules/.bin/gulp",
    "start": "node index.js",
    "postinstall": "run-s migrate build",
    "dev": "run-s build start"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/adonespitogo/dendroid-nodejs.git"
  },
  "keywords": [
    "dendroid",
    "nodejs",
    "express"
  ],
  "author": "Adones Pitogo",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/adonespitogo/dendroid-nodejs/issues"
  },
  "homepage": "https://github.com/adonespitogo/dendroid-nodejs#readme",
  "dependencies": {
    "body-parser": "^1.16.1",
    "del": "^3.0.0",
    "express": "^4.14.1",
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "^2.2.5",
    "gulp-concat": "^2.6.1",
    "gulp-inject": "^5.0.0",
    "gulp-uglify": "^3.0.1",
    "gulp-util": "^3.0.8",
    "mysql": "^2.13.0",
    "natives": "^1.1.6",
    "pg": "^7.9.0",
    "pg-hstore": "^2.3.2",
    "q": "^1.4.1",
    "randomstring": "^1.1.5",
    "require-dir": "^0.3.1",
    "sequelize": "^3.30.2",
    "sequelize-cli": "^2.5.1",
    "socket.io": "^1.7.2"
  },
  "devDependencies": {
    "gulp-jshint": "^2.1.0",
    "gulp-watch": "^4.3.11",
    "jshint": "^2.9.6",
    "npm-run-all": "^4.1.5"
  }
}

**Comment by carlossaldanha** [comment]
Thanks Brother Work fine.

**Comment by oathsaviour** [comment]
> the remote is still using node 12
> Sequelize [Node: 12.16.1, CLI: 2.7.0, ORM: 3.30.4]
> 
> the output should be this
> Sequelize [Node: 10.18.1, CLI: 2.7.0, ORM: 3.30.4]
> 
> please delete all the file from remote
> 
> then commit again with
> this package.json file
> 
> {
> "name": "androspy",
> "version": "1.0.0",
> "description": "NodeJS port of Dendroid server",
> "main": "index.js",
> "engines": {
> "node": "10.18.x"
> },
> "scripts": {
> "migrate": "./node_modules/.bin/sequelize db:migrate",
> "build": "./node_modules/.bin/gulp",
> "start": "node index.js",
> "postinstall": "run-s migrate build",
> "dev": "run-s build start"
> },
> "repository": {
> "type": "git",
> "url": "git+ssh://git@github.com/adonespitogo/dendroid-nodejs.git"
> },
> "keywords": [
> "dendroid",
> "nodejs",
> "express"
> ],
> "author": "Adones Pitogo",
> "license": "MIT",
> "bugs": {
> "url": "https://github.com/adonespitogo/dendroid-nodejs/issues"
> },
> "homepage": "https://github.com/adonespitogo/dendroid-nodejs#readme",
> "dependencies": {
> "body-parser": "^1.16.1",
> "del": "^3.0.0",
> "express": "^4.14.1",
> "gulp": "^3.9.1",
> "gulp-angular-templatecache": "^2.2.5",
> "gulp-concat": "^2.6.1",
> "gulp-inject": "^5.0.0",
> "gulp-uglify": "^3.0.1",
> "gulp-util": "^3.0.8",
> "mysql": "^2.13.0",
> "natives": "^1.1.6",
> "pg": "^7.9.0",
> "pg-hstore": "^2.3.2",
> "q": "^1.4.1",
> "randomstring": "^1.1.5",
> "require-dir": "^0.3.1",
> "sequelize": "^3.30.2",
> "sequelize-cli": "^2.5.1",
> "socket.io": "^1.7.2"
> },
> "devDependencies": {
> "gulp-jshint": "^2.1.0",
> "gulp-watch": "^4.3.11",
> "jshint": "^2.9.6",
> "npm-run-all": "^4.1.5"
> }
> }

thanks, brother that's really helped me, I didn't give attention to simple things.
