### ISSUE TITLE
Azure Deployment Node JS

### ISSUE THREAD

**Issue by asimajk1** [adonespitogo/AdoBot-IO#4]
I had deployed your project on Azure node JS server. Also i had created Mysql DB. Now i had hosted source code on server but unable to open any webpage. Kindly help me in finding the issue.
Following is my link and config.js file screenshot where i hosted.
https://android-projectx.azurewebsites.net/panel/

![azureissue](https://user-images.githubusercontent.com/22934044/39983847-8b9e3b0a-5772-11e8-9beb-e1ccf8848826.png)

**Comment by adonespitogo** [comment]
Did you set the necessary environment variables?

**Comment by adonespitogo** [comment]
These are the env varialbes you need to set:

`DATABASE_URL` - mysql database url
`ADMIN_USERNAME`
`ADMIN_PASSWORD`

**Comment by adonespitogo** [comment]
And of course `NODE_ENV=production`

**Comment by Mati018** [comment]
Can you please guide or provide the steps to deploy app on Azure.
