### ISSUE TITLE
Porblem on npm install

### ISSUE THREAD

**Issue by RedderKaz** [adonespitogo/AdoBot-IO#9]
When I install the server using "npm install" an error is shown:

Sequelize [Node: 8.11.1, CLI: 2.7.0, ORM: 3.30.4]

Task 'db:migrate;' is not in your gulpfile
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! androspy@1.0.0 postinstall: `sequelize db:migrate; ./node_modules/.bin/gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the androspy@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-01-04T13_01_35_786Z-debug.log

**Comment by adonespitogo** [comment]
I don't have time to debug this on windows. Try linux

**Comment by p2svn9x** [comment]
i got error on package.

> > pm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! androspy@1.0.0 dev: `gulp && npm start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the androspy@1.0.0 dev script 'gulp && npm start'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the androspy package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp && npm start
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs androspy
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls androspy
> npm ERR! There is likely additional logging out

**Comment by adonespitogo** [comment]
@p2svn9x Your nodejs/npm version is outdated. Try latest version of nodejs. Latest version is v10 for most systems.

**Comment by panpansh** [comment]
Sequelize [Node: 10.13.0, CLI: 2.7.0, ORM: 3.30.4]

Task 'db:migrate;' is not in your gulpfile
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! androspy@1.0.0 postinstall: `sequelize db:migrate; ./node_modules/.bin/gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the androspy@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by panpansh** [comment]
718 silly lifecycle androspy@1.0.0~postinstall: Args: [ '/d /s /c', 'sequelize db:migrate; ./node_modules/.bin/gulp' ]
719 silly lifecycle androspy@1.0.0~postinstall: Returned: code: 1  signal: null
720 info lifecycle androspy@1.0.0~postinstall: Failed to exec postinstall script

maybe the args ?

**Comment by panpansh** [comment]
using git bash do the same

**Comment by panpansh** [comment]
fix here : https://github.com/adonespitogo/AdoBot-IO/pull/13
